import { ColDef } from "ag-grid-community";

export const defaultColDef: ColDef = {
	filter: "agTextColumnFilter",
	floatingFilter: true,
	sortable: true,
};

export const columnDefs = [
	{ field: 'id', headerName: 'ID', sortable: true },
	{ field: 'name', headerName: 'Name' },
	{ field: 'code', headerName: 'Code' },
	{ field: 'activeSections', headerName: 'Active Sections', width: 150 },
	{ field: 'nearMapImageDate', headerName: 'Near Map Image Date', valueFormatter: (params: any) => new Date(params.value).toLocaleDateString() },
	{ field: 'builtOutSections', headerName: 'Built Sections', width: 150 },
	{ field: 'subdivisionStatusCode', headerName: 'Status Code' },
	{ field: 'fieldSurveyTerritoryId', headerName: 'Territory ID' },
	{ field: 'fieldSurveyTerritoryName', headerName: 'Territory Name' },
	{ field: 'futureSections', headerName: 'Future Sections', width: 150 },
	{ field: 'imageBoxId', headerName: 'Image Box ID' },
	{ field: 'latitude', headerName: 'Latitude' },
	{ field: 'longitude', headerName: 'Longitude' },
	{ field: 'community', headerName: 'Community' },
	{ field: 'county', headerName: 'County' },
	{ field: 'marketAbbreviation', headerName: 'Market Abbreviation' },
	{ field: 'marketId', headerName: 'Market ID' },
	{ field: 'marketName', headerName: 'Market Name' },
	{ field: 'mostRecentIPointBatchDate', headerName: 'Recent Batch Date' },
	{ field: 'subdivisionGeometryBoundaryId', headerName: 'Boundary ID' },
	{ field: 'subdivisionGeometryBoundingBoxId', headerName: 'Box ID' },
	{ field: 'subdivisionGeometryId', headerName: 'Subdivision Geometry ID' },
	{ field: 'subdivisionGeometryIntelligenceBoundaryId', headerName: 'Intelligence Boundary ID' },
	{ field: 'subdivisionGeometryIntelligenceBoundaryStatusChangeDate', headerName: 'Status Change Date' },
	{ field: 'subdivisionGeometryIntelligenceBoundaryStatusCode', headerName: 'Boundary Status Code' },
	{ field: 'subdivisionGeometryIntelligenceBoundaryStatusId', headerName: 'Status ID' },
	{ field: 'subdivisionSpecificStatus', headerName: 'Specific Status' },
	{ field: 'subdivisionStatusId', headerName: 'Status ID' },
	{ field: 'surveyMethodCode', headerName: 'Method Code' },
	{ field: 'surveyMethodId', headerName: 'Method ID' },
	{ field: 'totalLots', headerName: 'Total Lots' },
	{ field: 'validatediPoints', headerName: 'I-Points' },
	{ field: 'zoom17Date', headerName: 'Zoom 17 Date' },
	{ field: 'zoom18Date', headerName: 'Zoom 18 Date' },
	{ field: 'iPoints', headerName: 'iPoints' },
];
